function report = build_selected_methods_report(results,problem,cfg)
%BUILD_SELECTED_METHODS_REPORT
% Build a comparison report for any selected method subset.
%
% ========================================================================
% FAIR RUNTIME CONVENTION
% ========================================================================
%
% For every method:
%
%   RawMethodTimeSec
%       = complete algorithmic time required to produce the reported
%         RAW feasible partition.
%
%   PostprocessTimeSec
%       = project-wide common 2-opt time only.
%
%   TotalMethodTimeSec
%       = RawMethodTimeSec + PostprocessTimeSec.
%
% Method-specific internal timings such as
%
%   - linprog
%   - ADMM kernel
%   - projection
%   - Z construction
%   - rounding
%   - internal N2
%
% are diagnostics only and are NOT the main cross-method runtime metric.
%
% All quality values are reported on the common J_common scale.
%
% IMPORTANT:
% Calculations use full double precision.
% Rounding to four decimals is ONLY for the displayed summary table.

    Method = strings(0,1);
    Stage = strings(0,1);

    JCommon = zeros(0,1);

    Iterations = zeros(0,1);
    AvgTimePerIterSec = zeros(0,1);

    RawMethodTimeSec = zeros(0,1);
    PostprocessTimeSec = zeros(0,1);
    TotalMethodTimeSec = zeros(0,1);

    %% ============================================================
    % eADMM
    %
    % Raw time:
    % DNN/SDP solve + Vc rounding required to obtain the raw
    % feasible partition.
    %
    % Certification-only MET/LB work is NOT included.
    % ============================================================

    if isfield(results,'eadmm')

        E = results.eadmm;

        raw_time = ...
            E.solution_time_raw;

        addrow( ...
            sprintf('eADMM+Vc best-of-%d',numel(E.vc_jcommon)), ...
            'raw', ...
            E.best_vc_jcommon, ...
            E.dnn_iterations, ...
            E.dnn_avg_iter_time, ...
            raw_time, ...
            0, ...
            raw_time);

        if cfg.eadmm.use_2opt

            post_time = ...
                E.two_opt_time;

            total_time = ...
                E.solution_time_with_2opt;

            addrow( ...
                sprintf('eADMM+Vc+common2opt best-of-%d', ...
                    numel(E.vc2_jcommon)), ...
                'same 2opt', ...
                E.best_vc2_jcommon, ...
                E.dnn_iterations, ...
                E.dnn_avg_iter_time, ...
                raw_time, ...
                post_time, ...
                total_time);
        end
    end

    %% ============================================================
    % Lp family
    %
    % lp_balanced_algorithm2 is timed as one complete call.
    %
    % Hence raw time already includes:
    %
    %   iterations
    %   projection
    %   line search
    %   paper rounding
    %   internal N2, if enabled
    %
    % common 2-opt is kept separate.
    % ============================================================

    if isfield(results,'lp') && ...
            isfield(results.lp,'enabled') && ...
            results.lp.enabled

        L = results.lp;

        if isfield(L,'alg2') && ...
                L.alg2.enabled

            add_lp_variant( ...
                L.alg2, ...
                'Lp-Alg2');
        end

        if isfield(L,'bs') && ...
                L.bs.enabled

            add_lp_variant( ...
                L.bs, ...
                'Lp-bs');
        end
    end

    %% ============================================================
    % MMD-LP
    %
    % Raw time includes:
    %
    %   Z construction
    %   + LP model construction
    %   + linprog
    %   + LP postsolve
    %   + top-k rounding
    %   + sequential P/Q updates
    %
    % Exact brute-force audit is diagnostic only and must already be
    % excluded from M.raw_wall_time.
    % ============================================================

    if isfield(results,'mmdlp')

        M = results.mmdlp;

        raw_time = ...
            M.raw_wall_time;

        n_lp = ...
            M.num_lp_solves;

        % Average complete time per sequential LP stage.
        avg_stage_time = ...
            raw_time / max(n_lp,1);

        addrow( ...
            'MMD-LP', ...
            'raw', ...
            M.raw_jcommon, ...
            n_lp, ...
            avg_stage_time, ...
            raw_time, ...
            0, ...
            raw_time);

        if cfg.two_opt.enabled && ...
                cfg.mmdlp.use_common_2opt

            post_time = ...
                M.two_opt_time;

            addrow( ...
                'MMD-LP+common2opt', ...
                'same 2opt', ...
                M.refined_jcommon, ...
                n_lp, ...
                avg_stage_time, ...
                raw_time, ...
                post_time, ...
                M.total_time);
        end
    end

    %% ============================================================
    % Random
    %
    % If best-of-R is reported, generation time of all R candidates
    % is included because all R candidates must be generated before
    % choosing the best.
    % ============================================================

    if isfield(results,'random')

        R = results.random;

        rid = ...
            R.best_raw_id;

        raw_time = ...
            sum(R.gen_time,'omitnan');

        addrow( ...
            sprintf('Random best-of-%d',numel(R.raw_jcommon)), ...
            'raw', ...
            R.raw_jcommon(rid), ...
            NaN, ...
            NaN, ...
            raw_time, ...
            0, ...
            raw_time);

        if cfg.two_opt.enabled

            r2 = ...
                R.best_refined_id;

            post_time = ...
                sum(R.local_time,'omitnan');

            addrow( ...
                sprintf('Random+common2opt best-of-%d', ...
                    numel(R.refined_jcommon)), ...
                'same 2opt', ...
                R.refined_jcommon(r2), ...
                NaN, ...
                NaN, ...
                raw_time, ...
                post_time, ...
                R.wall_time);
        end
    end

    %% ============================================================
    % Vector
    %
    % Current implementation:
    %
    %   solve_time
    %       split-ADMM iterations
    %
    %   extract_time
    %       Z construction + initialization + discrete extraction
    %
    % Their sum is the complete raw method time.
    % ============================================================

    if isfield(results,'vector')

        V = results.vector;

        raw_time = ...
            V.solve_time + ...
            V.extract_time;

        % Method-level average.
        avg_iter_time = ...
            raw_time / ...
            max(V.iterations,1);

        addrow( ...
            'Vector', ...
            'raw', ...
            V.raw_jcommon, ...
            V.iterations, ...
            avg_iter_time, ...
            raw_time, ...
            0, ...
            raw_time);

        if cfg.two_opt.enabled && ...
                cfg.vector.use_common_2opt

            post_time = ...
                V.two_opt_time;

            addrow( ...
                'Vector+common2opt', ...
                'same 2opt', ...
                V.refined_jcommon, ...
                V.iterations, ...
                avg_iter_time, ...
                raw_time, ...
                post_time, ...
                V.total_time);
        end
    end

    %% ============================================================
    % Matrix
    %
    % Raw method time:
    %
    %   warm-start upstream/conversion, if external
    %   + Matrix iterative solver
    %   + final discrete extraction.
    %
    % For uniform/random internal initialization,
    % warmstart_overhead_time is zero.
    % ============================================================

    if isfield(results,'matrix')

        M = results.matrix;

        ids = ...
            M.valid_ids(:)';

        mb = ...
            M.best_raw_id;

        total_solver_time = ...
            sum(M.solve_time(ids),'omitnan');

        total_extract_time = ...
            sum(M.extract_time(ids),'omitnan');

        warmstart_overhead = ...
            M.warmstart_overhead_time;

        raw_time = ...
            warmstart_overhead + ...
            total_solver_time + ...
            total_extract_time;

        total_iter = ...
            sum(M.iterations(ids),'omitnan');

        % Average iterative-solver time only.
        avg_iter_time = ...
            total_solver_time / ...
            max(total_iter,1);

        addrow( ...
            sprintf('Matrix best-of-%d',numel(ids)), ...
            'raw', ...
            M.raw_jcommon(mb), ...
            total_iter, ...
            avg_iter_time, ...
            raw_time, ...
            0, ...
            raw_time);

        if cfg.two_opt.enabled

            m2 = ...
                M.best_refined_id;

            total_local = ...
                sum(M.local_time(ids),'omitnan');

            addrow( ...
                sprintf('Matrix+common2opt best-of-%d',numel(ids)), ...
                'same 2opt', ...
                M.refined_jcommon(m2), ...
                total_iter, ...
                avg_iter_time, ...
                raw_time, ...
                total_local, ...
                raw_time+total_local);
        end
    end

    %% ============================================================
    % Basic check
    % ============================================================

    if isempty(JCommon)
        error( ...
            'No result rows were generated. Check cfg.methods.run.');
    end

    %% ============================================================
    % Best feasible discrete solution
    % ============================================================

    best_feasible = ...
        min(JCommon,[],'omitnan');

    GapToBestDiscretePct = ...
        100*(JCommon-best_feasible) ./ ...
        max(abs(best_feasible),eps);

    %% ============================================================
    % Safe lower bound
    % ============================================================

    safe_lb = NaN;
    safe_valid = false;

    safe_source = ...
        "not available (eADMM not run)";

    if isfield(results,'eadmm')

        E = results.eadmm;

        if isfield(E,'safe_jcommon_lower_bound')

            safe_lb = ...
                E.safe_jcommon_lower_bound;
        end

        if isfield(E,'safe_lower_bound_numerically_feasible')

            safe_valid = ...
                isfinite(safe_lb) && ...
                E.safe_lower_bound_numerically_feasible;
        end

        if isfield(E,'safe_lower_bound_source')

            safe_source = ...
                string(E.safe_lower_bound_source);
        end

        if safe_valid

            tol = ...
                1e-8 * ...
                max([ ...
                    1, ...
                    abs(best_feasible), ...
                    abs(safe_lb)]);

            if safe_lb > best_feasible + tol

                warning( ...
                    ['Safe J_common lower bound %.12e exceeds ', ...
                     'the best feasible J_common %.12e. ', ...
                     'Certified gaps are suppressed.'], ...
                    safe_lb, ...
                    best_feasible);

                safe_valid = false;
            end
        end
    end

    %% ============================================================
    % Certified gap
    % ============================================================

    if safe_valid

        CertifiedAbsGap = ...
            JCommon-safe_lb;

        tol = ...
            1e-8 * ...
                max([ ...
                    1, ...
                    abs(best_feasible), ...
                    abs(safe_lb)]);

        CertifiedAbsGap( ...
            CertifiedAbsGap<0 & ...
            CertifiedAbsGap>=-tol) = 0;

        CertifiedGapPct = ...
            100*CertifiedAbsGap ./ ...
            max(abs(JCommon),eps);

    else

        CertifiedAbsGap = ...
            nan(size(JCommon));

        CertifiedGapPct = ...
            nan(size(JCommon));
    end

    %% ============================================================
    % Summary table
    %
    % Keep full-precision arrays above for all calculations.
    % Only table values are rounded to 4 decimals.
    % ============================================================

    JCommonTable = ...
        round4(JCommon);

    CertifiedAbsGapTable = ...
        round4(CertifiedAbsGap);

    CertifiedGapPctTable = ...
        round4(CertifiedGapPct);

    GapToBestDiscretePctTable = ...
        round4(GapToBestDiscretePct);

    AvgTimePerIterSecTable = ...
        round4(AvgTimePerIterSec);

    RawMethodTimeSecTable = ...
        round4(RawMethodTimeSec);

    PostprocessTimeSecTable = ...
        round4(PostprocessTimeSec);

    TotalMethodTimeSecTable = ...
        round4(TotalMethodTimeSec);

    summary_table = table( ...
        Method, ...
        Stage, ...
        JCommonTable, ...
        CertifiedAbsGapTable, ...
        CertifiedGapPctTable, ...
        GapToBestDiscretePctTable, ...
        Iterations, ...
        AvgTimePerIterSecTable, ...
        RawMethodTimeSecTable, ...
        PostprocessTimeSecTable, ...
        TotalMethodTimeSecTable, ...
        'VariableNames',{ ...
            'Method', ...
            'Stage', ...
            'JCommon', ...
            'CertifiedAbsGap', ...
            'CertifiedGapPct', ...
            'GapToBestDiscretePct', ...
            'Iterations', ...
            'AvgTimePerIterSec', ...
            'RawMethodTimeSec', ...
            'PostprocessTimeSec', ...
            'TotalMethodTimeSec'});

    %% ============================================================
    % Report structure
    % ============================================================

    report = struct();

    report.selected_methods = ...
        cfg.methods.run;

    report.summary_table = ...
        summary_table;

    % Full precision retained here.
    report.best_feasible_jcommon = ...
        best_feasible;

    report.safe_jcommon_lower_bound = ...
        safe_lb;

    report.safe_lower_bound_valid = ...
        safe_valid;

    report.safe_lower_bound_source = ...
        safe_source;

    if safe_valid

        report.best_certified_abs_gap = ...
            best_feasible-safe_lb;

        if report.best_certified_abs_gap < 0 && ...
                report.best_certified_abs_gap >= -tol

            report.best_certified_abs_gap = 0;
        end

        report.best_certified_gap_pct = ...
            100 * ...
            report.best_certified_abs_gap / ...
            max(abs(best_feasible),eps);

    else

        report.best_certified_abs_gap = NaN;
        report.best_certified_gap_pct = NaN;
    end

    report.problem_build_time = ...
        problem.build_time;

    %% ============================================================
    % Nested helper: Lp variants
    % ============================================================

    function add_lp_variant(V,name)

        ids = ...
            V.valid_ids(:)';

        bid = ...
            V.best_raw_id;

        % Complete Algorithm-2 call time.
        raw_time_lp = ...
            sum(V.solve_time(ids),'omitnan');

        total_iter_lp = ...
            sum(V.inner_iterations(ids),'omitnan');

        avg_lp = ...
            raw_time_lp / ...
            max(total_iter_lp,1);

        addrow( ...
            sprintf('%s best-of-%d',name,numel(ids)), ...
            'raw', ...
            V.raw_jcommon(bid), ...
            total_iter_lp, ...
            avg_lp, ...
            raw_time_lp, ...
            0, ...
            raw_time_lp);

        if cfg.lp.use_common_2opt

            b2 = ...
                V.best_refined_id;

            post_time_lp = ...
                sum(V.local_time(ids),'omitnan');

            addrow( ...
                sprintf('%s+common2opt best-of-%d', ...
                    name,numel(ids)), ...
                'same 2opt', ...
                V.refined_jcommon(b2), ...
                total_iter_lp, ...
                avg_lp, ...
                raw_time_lp, ...
                post_time_lp, ...
                raw_time_lp+post_time_lp);
        end
    end

    %% ============================================================
    % Nested helper: append one row
    % ============================================================

    function addrow( ...
            method, ...
            stage, ...
            jcommon, ...
            iterations, ...
            avg_iter_time, ...
            raw_time, ...
            post_time, ...
            total_time)

        Method(end+1,1) = ...
            string(method);

        Stage(end+1,1) = ...
            string(stage);

        JCommon(end+1,1) = ...
            jcommon;

        Iterations(end+1,1) = ...
            iterations;

        AvgTimePerIterSec(end+1,1) = ...
            avg_iter_time;

        RawMethodTimeSec(end+1,1) = ...
            raw_time;

        PostprocessTimeSec(end+1,1) = ...
            post_time;

        TotalMethodTimeSec(end+1,1) = ...
            total_time;
    end

    %% ============================================================
    % Nested helper: display rounding only
    % ============================================================

    function y = round4(x)

        y = x;

        finite_id = ...
            isfinite(x);

        y(finite_id) = ...
            round(x(finite_id)*1e4)/1e4;
    end
end