function print_selected_methods_report(report,results,problem,cfg)
%PRINT_SELECTED_METHODS_REPORT Print a report for any selected method subset.
%
% All solver-independent quality values are reported on the common
% J_common scale.
%
% Time convention:
%
%   SolveTimeSec
%       = method-specific core solve time
%
%   InitExtractTimeSec
%       = initialization / rounding / extraction / construction overhead
%
%   LocalSearchTimeSec
%       = common project-wide 2-opt time
%
%   TotalMethodTimeSec
%       = end-to-end time used in the comparison table
%
% For MMD-LP:
%
%   Iterations
%       = number of sequential LP solves, namely num_batches - 1
%
%   AvgTimePerIterSec
%       = average linprog solve time per sequential LP subproblem.
%

    fprintf('\n');
    fprintf('======================================================================\n');
    fprintf('★ Selected-method comparison report ★\n');
    fprintf('实际运行方法：%s\n', ...
        strjoin(report.selected_methods,' -> '));
    fprintf('统一目标：J_common，越小越好。\n');
    fprintf('======================================================================\n');

    %% ============================================================
    % Final comparison table
    % ============================================================

    fprintf('\n');
    fprintf('==================== 最终对比表 ====================\n');

    disp(report.summary_table);

    fprintf([ ...
        '时间口径：SolveTimeSec=核心求解时间；', ...
        'InitExtractTimeSec=构造/rounding/解提取/warm-start等开销；', ...
        'LocalSearchTimeSec=统一 common 2-opt；', ...
        'TotalMethodTimeSec=端到端时间。\n']);

    fprintf([ ...
        'MMD-LP 的 Iterations 表示 sequential LP solve 次数，', ...
        'AvgTimePerIterSec 表示平均每个 LP 子问题的 linprog 时间。\n']);

    %% ============================================================
    % Global best / certified lower bound
    % ============================================================

    fprintf('\n');
    fprintf('*本次找到的最好可行 J_common = %.10e*\n', ...
        report.best_feasible_jcommon);

    if report.safe_lower_bound_valid

        fprintf('*安全 J_common 下界 = %.10e*\n', ...
            report.safe_jcommon_lower_bound);

        fprintf('*最好解 certified relative gap = %.6f%%*\n', ...
            report.best_certified_gap_pct);

        fprintf('安全下界来源 = %s。\n', ...
            report.safe_lower_bound_source);

    else

        fprintf([ ...
            '安全下界 / certified gap：', ...
            '不可用或未运行 eADMM 认证分支。\n']);
    end

    %% ============================================================
    % eADMM
    % ============================================================

    if isfield(results,'eadmm')

        E = results.eadmm;

        fprintf('\n');
        fprintf('[eADMM]\n');

        fprintf('*best raw Vc J_common = %.10e*\n', ...
            E.best_vc_jcommon);

        fprintf([ ...
            '*DNN 迭代数 = %d* | ', ...
            '*sec/iter = %.6e* | ', ...
            '*DNN solve = %.6f 秒*\n'], ...
            E.dnn_iterations, ...
            E.dnn_avg_iter_time, ...
            E.solve_time);

        fprintf('*raw 解生成总时间 = %.6f 秒*\n', ...
            E.solution_time_raw);

        if cfg.eadmm.use_2opt

            fprintf([ ...
                '*best Vc+2opt J_common = %.10e* | ', ...
                '*端到端时间 = %.6f 秒*\n'], ...
                E.best_vc2_jcommon, ...
                E.solution_time_with_2opt);
        end

        if report.safe_lower_bound_valid

            fprintf('*安全 J_common 下界 = %.10e*\n', ...
                report.safe_jcommon_lower_bound);
        end
    end

    %% ============================================================
    % Lp family
    % ============================================================

    if isfield(results,'lp') && ...
            isfield(results.lp,'enabled') && ...
            results.lp.enabled

        L = results.lp;

        fprintf('\n');
        fprintf('[Lp]\n');

        if isfield(L,'alg2') && ...
                L.alg2.enabled

            print_lp_variant( ...
                L.alg2, ...
                'Lp-Alg2');
        end

        if isfield(L,'bs') && ...
                L.bs.enabled

            print_lp_variant( ...
                L.bs, ...
                'Lp-bs');
        end
    end

    %% ============================================================
    % MMD-LP
    % ============================================================

    if isfield(results,'mmdlp')

        M = results.mmdlp;

        fprintf('\n');
        fprintf('[MMD-LP]\n');

        fprintf([ ...
            '方法：Banerjee & Chakraborty AAAI-21 ', ...
            'Eq. (10) LP relaxation + top-k rounding。\n']);

        fprintf('*raw J_common = %.10e*\n', ...
            M.raw_jcommon);

        fprintf('*sequential LP solve 次数 = %d*\n', ...
            M.num_lp_solves);

        avg_lp_time = ...
            M.solve_time / max(M.num_lp_solves,1);

        fprintf('*平均每个 LP solve 时间 = %.6e 秒*\n', ...
            avg_lp_time);

        fprintf([ ...
            'LP solve 累计时间 = %.6f 秒 | ', ...
            'Z build 累计时间 = %.6f 秒 | ', ...
            'rounding/processing 累计时间 = %.6f 秒\n'], ...
            M.solve_time, ...
            M.build_time, ...
            M.rounding_time);

        fprintf('*raw wall time = %.6f 秒*\n', ...
            M.raw_wall_time);

        if isfield(M,'lp_num_variables') && ...
                ~isempty(M.lp_num_variables)

            valid_vars = ...
                M.lp_num_variables(M.lp_num_variables > 0);

            if ~isempty(valid_vars)

                fprintf([ ...
                    'LP 规模：首个子问题变量数=%d | ', ...
                    '最大变量数=%d\n'], ...
                    valid_vars(1), ...
                    max(valid_vars));
            end
        end

        if isfield(M,'lp_num_inequalities') && ...
                ~isempty(M.lp_num_inequalities)

            valid_ineq = ...
                M.lp_num_inequalities( ...
                    M.lp_num_inequalities > 0);

            if ~isempty(valid_ineq)

                fprintf([ ...
                    'LP 规模：首个子问题 inequality 数=%d | ', ...
                    '最大 inequality 数=%d\n'], ...
                    valid_ineq(1), ...
                    max(valid_ineq));
            end
        end

        if isfield(M,'lp_feasibility_residual') && ...
                ~isempty(M.lp_feasibility_residual)

            valid_resid = ...
                M.lp_feasibility_residual( ...
                    isfinite(M.lp_feasibility_residual));

            if ~isempty(valid_resid)

                fprintf('*最大 LP feasibility residual = %.3e*\n', ...
                    max(valid_resid));
            end
        end

        if isfield(M,'relaxed_cardinality_residual') && ...
                ~isempty(M.relaxed_cardinality_residual)

            valid_card = ...
                M.relaxed_cardinality_residual( ...
                    isfinite(M.relaxed_cardinality_residual));

            if ~isempty(valid_card)

                fprintf('*最大 relaxed cardinality residual = %.3e*\n', ...
                    max(valid_card));
            end
        end

        if isfield(M,'lp_objective_per_batch') && ...
                isfield(M,'rounded_iqp_objective_per_batch')

            lp_obj = ...
                M.lp_objective_per_batch;

            iq_obj = ...
                M.rounded_iqp_objective_per_batch;

            valid_obj = ...
                isfinite(lp_obj) & ...
                isfinite(iq_obj);

            if any(valid_obj)

                first_id = ...
                    find(valid_obj,1,'first');

                fprintf([ ...
                    '首个 LP 子问题：', ...
                    'relaxation objective = %.10e | ', ...
                    'rounded IQP objective = %.10e\n'], ...
                    lp_obj(first_id), ...
                    iq_obj(first_id));
            end
        end

        if cfg.two_opt.enabled && ...
                cfg.mmdlp.use_common_2opt

            fprintf('*MMD-LP + common2opt J_common = %.10e*\n', ...
                M.refined_jcommon);

            fprintf([ ...
                'common2opt 时间 = %.6f 秒 | ', ...
                '*端到端时间 = %.6f 秒*\n'], ...
                M.two_opt_time, ...
                M.total_time);
        end
    end

    %% ============================================================
    % Random
    % ============================================================

    if isfield(results,'random')

        R = results.random;

        rid = R.best_raw_id;

        fprintf('\n');
        fprintf('[Random]\n');

        fprintf([ ...
            '*best-of-%d raw J_common = %.10e* | ', ...
            '*累计生成时间 = %.6f 秒*\n'], ...
            numel(R.raw_jcommon), ...
            R.raw_jcommon(rid), ...
            sum(R.gen_time,'omitnan'));

        if cfg.two_opt.enabled

            r2 = R.best_refined_id;

            fprintf([ ...
                '*best +2opt J_common = %.10e* | ', ...
                '*总 wall time = %.6f 秒*\n'], ...
                R.refined_jcommon(r2), ...
                R.wall_time);
        end
    end

    %% ============================================================
    % Vector
    % ============================================================

    if isfield(results,'vector')

        V = results.vector;

        fprintf('\n');
        fprintf('[Vector]\n');

        fprintf([ ...
            'raw J_common = %.10e | ', ...
            'iterations = %d | ', ...
            'solve = %.6f 秒 | ', ...
            'extraction = %.6f 秒\n'], ...
            V.raw_jcommon, ...
            V.iterations, ...
            V.solve_time, ...
            V.extract_time);

        fprintf([ ...
            'Vector ADMM exact-binary batches = %d/%d | ', ...
            'fallback batches = %d\n'], ...
            V.exact_batches, ...
            problem.num_batches, ...
            V.fallback_batches);

        if cfg.two_opt.enabled && ...
                cfg.vector.use_common_2opt

            fprintf([ ...
                'Vector+2opt J_common = %.10e | ', ...
                '2opt = %.6f 秒 | ', ...
                'total = %.6f 秒\n'], ...
                V.refined_jcommon, ...
                V.two_opt_time, ...
                V.total_time);
        end
    end

    %% ============================================================
    % Matrix
    % ============================================================

    if isfield(results,'matrix')

        M = results.matrix;

        bid = M.best_raw_id;
        B = M.raw{bid};

        ids = M.valid_ids(:)';

        fprintf('\n');
        fprintf('[Matrix]\n');

        fprintf('初始化方式 = %s。\n', ...
            string(M.init_mode));

        if M.warmstart.is_external

            fprintf('warm start = %s。\n', ...
                string(M.warmstart_label));

            fprintf('warm-start 上游+转换时间 = %.6f 秒。\n', ...
                M.warmstart_overhead_time);
        end

        fprintf('*best raw J_common = %.10e*\n', ...
            M.raw_jcommon(bid));

        fprintf([ ...
            '*best start 迭代数 = %d* | ', ...
            '*sec/iter = %.6e* | ', ...
            '*solve = %.6f 秒*\n'], ...
            B.iterations, ...
            B.avg_iter_time, ...
            B.solve_time);

        if isfield(B,'early_exist_triggered')

            fprintf('early_exist triggered = %d', ...
                B.early_exist_triggered);

            if B.early_exist_triggered

                fprintf(' | trigger iter = %d', ...
                    B.early_exist_iteration);
            end

            fprintf('\n');
        end

        fprintf([ ...
            'best-of-%d Matrix 自身累计 solve+extract = %.6f 秒。\n'], ...
            numel(ids), ...
            sum(M.solve_time(ids),'omitnan') + ...
            sum(M.extract_time(ids),'omitnan'));

        if cfg.two_opt.enabled

            m2 = M.best_refined_id;

            fprintf('*best +2opt J_common = %.10e*\n', ...
                M.refined_jcommon(m2));
        end
    end

    %% ============================================================
    % Shared construction time
    % ============================================================

    fprintf('\n');

    fprintf([ ...
        '共享问题构造时间 = %.6f 秒', ...
        '（不计入各方法运行时间）。\n'], ...
        problem.build_time);

    %% ============================================================
    % Nested helper: Lp variant report
    % ============================================================

    function print_lp_variant(V,name)

        ids = V.valid_ids(:)';
        bid = V.best_raw_id;

        total_inner = ...
            sum(V.inner_iterations(ids),'omitnan');

        total_solve = ...
            sum(V.solve_time(ids),'omitnan');

        fprintf([ ...
            '*%s best raw J_common = %.10e* | ', ...
            '*累计 inner = %d* | ', ...
            '*累计 solve = %.6f 秒*\n'], ...
            name, ...
            V.raw_jcommon(bid), ...
            total_inner, ...
            total_solve);

        if cfg.lp.use_common_2opt

            b2 = V.best_refined_id;

            total_local = ...
                sum(V.local_time(ids),'omitnan');

            fprintf([ ...
                '*%s +common2opt J_common = %.10e* | ', ...
                'common2opt = %.6f 秒\n'], ...
                name, ...
                V.refined_jcommon(b2), ...
                total_local);
        end
    end
end