function result = solve_matrix_batching_vc(problem, opts)
%SOLVE_MATRIX_BATCHING_VC
%
% Matrix ADMM -> KKT stopping -> Y*Y' -> same eADMM Vc(10).
%
% Continuous stopping:
%
%   max(r, ||X-Y||_F) <= opts.epsikkt.
%
% Rounding:
%
%   S = Y*Y'
%
% followed by the SAME kequi_rounding routine used by eADMM,
% with 10 restarts by default.


%% ======================== Defaults ======================================

    if ~isfield(opts,'epsikkt') || isempty(opts.epsikkt)

        error( ...
            ['solve_matrix_batching_vc requires ', ...
             'opts.epsikkt.']);
    end


    if ~isfield(opts,'vc_restarts')
        opts.vc_restarts = 10;
    end

    if ~isfield(opts,'vc_seed_base')
        opts.vc_seed_base = 9001;
    end

    if ~isfield(opts,'matrix_clean')
        opts.matrix_clean = true;
    end

    if ~isfield(opts,'matrix_clean_fast')
        opts.matrix_clean_fast = true;
    end

    if ~isfield(opts,'matrix_detail')
        opts.matrix_detail = false;
    end

    if ~isfield(opts,'verbose')
        opts.verbose = false;
    end

    if ~isfield(opts,'eta_adapt_enabled')
        opts.eta_adapt_enabled = false;
    end

    if ~isfield(opts,'eta_stage_initial')
        opts.eta_stage_initial = -1;
    end

    if ~isfield(opts,'n_outer')
        opts.n_outer = 1;
    end

    if opts.n_outer ~= 1

        error( ...
            ['Matrix-KKT+Vc currently expects ', ...
             'opts.n_outer=1.']);
    end


%% ======================== Data ==========================================

    A = ...
        problem.A;

    G = ...
        problem.G;

    beta0 = ...
        opts.beta0;

    c = ...
        opts.c;


    [N,B] = ...
        size(G);


%% ======================== eta ===========================================

    eta_reference = ...
        opts.eta;


    if opts.eta_adapt_enabled

        eta_state = ...
            opts.eta_stage_initial;

    else

        eta_state = ...
            eta_reference;
    end


    eta_state_initial = ...
        eta_state;


%% ======================== Initialization ================================

    if ~isfield(opts,'init_mode')
        opts.init_mode = "uniform";
    end


    switch string(opts.init_mode)

        case "uniform"

            X = ...
                ones(N,B)/B ...
                + ...
                (rand(N,B)-0.5) ...
                * ...
                (1/B) ...
                * ...
                1e-2;

            Y = ...
                ones(N,B)/B ...
                + ...
                (rand(N,B)-0.5) ...
                * ...
                (1/B) ...
                * ...
                1e-2;


        case "zero"

            X = ...
                zeros(N,B);

            Y = ...
                zeros(N,B);


        case "provided"

            if ~isfield(opts,'X0') || ...
                    isempty(opts.X0)

                error( ...
                    'init_mode="provided" requires opts.X0.');
            end


            X = ...
                double(opts.X0);


            if isfield(opts,'Y0') && ...
                    ~isempty(opts.Y0)

                Y = ...
                    double(opts.Y0);

            else

                Y = ...
                    X;
            end


        otherwise

            error( ...
                'Unknown Matrix init_mode: %s', ...
                string(opts.init_mode));
    end


%% ======================== Header ========================================

    fprintf('\n');
    fprintf('============================================================\n');
    fprintf('[Matrix-KKT+Vc]\n');
    fprintf('backend = PURE MATLAB\n');
    fprintf('epsikkt = %.6e\n',opts.epsikkt);
    fprintf('Vc restarts = %d\n',opts.vc_restarts);
    fprintf('Vc seed base = %d\n',opts.vc_seed_base);
    fprintf('Vc input = Y_kkt * Y_kkt''\n');
    fprintf('============================================================\n');


%% ======================== Continuous Matrix stage =======================

    tsolve = ...
        tic;


    [ ...
        X, ...
        Y, ...
        error_list, ...
        flag, ...
        Lambda_history, ...
        r_history, ...
        dxy_history, ...
        round_y_history, ...
        fractional_ratio_history, ...
        lambda_fnorm, ...
        dx_history, ...
        beta_history, ...
        ori_obj_history, ...
        eta_state_final, ...
        eta_update_history, ...
        eta_update_count, ...
        actual_iter, ...
        final_error, ...
        final_r, ...
        final_dxy ...
    ] = ...
        splitadmm_vc( ...
            A, ...
            G, ...
            eta_state, ...
            beta0, ...
            c, ...
            1, ...
            opts.max_iter, ...
            X, ...
            Y, ...
            opts.tol, ...
            opts.use_adaptive_beta, ...
            opts);


    solve_time = ...
        toc(tsolve);


%% ======================== Vc(10) ========================================

    vc = ...
        matrix_vc_rounding10( ...
            Y, ...
            problem, ...
            opts);


%% ======================== Result ========================================

    result = struct();


    result.method = ...
        "Matrix-KKT+Vc";


    result.backend = ...
        "PURE MATLAB";


    result.X = ...
        X;

    result.Y = ...
        Y;


    result.S_vc = ...
        vc.S;


    result.I = ...
        vc.best_I;

    result.P = ...
        vc.best_P;


    result.metrics = ...
        vc.best_metrics;


    result.best_vc_jcommon = ...
        vc.best_jcommon;

    result.best_vc_restart = ...
        vc.best_restart;


    result.vc_restarts = ...
        vc.num_restarts;

    result.vc_seed_base = ...
        vc.seed_base;

    result.vc_rounding_time = ...
        vc.rounding_time;

    result.vc_restart_results = ...
        vc.restart_results;


    result.flag = ...
        flag;


    result.epsikkt = ...
        opts.epsikkt;

    result.kkt_residual = ...
        final_error;

    result.final_r = ...
        final_r;

    result.final_dxy = ...
        final_dxy;


    result.iterations = ...
        actual_iter;


    result.solve_time = ...
        solve_time;


    result.extract_time = ...
        vc.rounding_time;


    result.total_time = ...
        solve_time ...
        + ...
        vc.rounding_time;


    result.avg_iter_time = ...
        solve_time ...
        / ...
        max(actual_iter,1);


    result.eta_stage_initial = ...
        eta_state_initial;

    result.eta_stage_final = ...
        eta_state_final;

    result.eta_final = ...
        max(eta_state_final,0);

    result.eta_update_count = ...
        eta_update_count;

    result.eta_update_history = ...
        eta_update_history;


    result.error_history = ...
        error_list;

    result.r_history = ...
        r_history;

    result.dxy_history = ...
        dxy_history;

    result.round_y_history = ...
        round_y_history;

    result.fractional_ratio_history = ...
        fractional_ratio_history;

    result.lambda_history = ...
        Lambda_history;

    result.lambda_fnorm = ...
        lambda_fnorm;

    result.dx_history = ...
        dx_history;

    result.beta_history = ...
        beta_history;

    result.ori_obj_history = ...
        ori_obj_history;


%% ======================== Summary =======================================

    fprintf('\n');
    fprintf('==================== Matrix-KKT+Vc result ====================\n');

    fprintf( ...
        '*KKT stop iteration = %d*\n', ...
        result.iterations);

    fprintf( ...
        '*KKT residual = %.6e*\n', ...
        result.kkt_residual);

    fprintf( ...
        '  r = %.6e\n', ...
        result.final_r);

    fprintf( ...
        '  ||X-Y||_F = %.6e\n', ...
        result.final_dxy);

    fprintf( ...
        'eta state final = %.10g\n', ...
        result.eta_stage_final);

    fprintf( ...
        '*continuous solve time = %.6f s*\n', ...
        result.solve_time);

    fprintf( ...
        '*Vc(10) rounding time = %.6f s*\n', ...
        result.vc_rounding_time);

    fprintf( ...
        '*best Vc J_common = %.10e* (restart %d)\n', ...
        result.best_vc_jcommon, ...
        result.best_vc_restart);

    fprintf( ...
        '*total solve+Vc time = %.6f s*\n', ...
        result.total_time);

    fprintf('============================================================\n');

end