function [ ...
    X, ...
    Y, ...
    error_list, ...
    flag, ...
    Lambda_history, ...
    r_collect, ...
    dxy_collect, ...
    round_y_collect, ...
    y_non_ratio, ...
    lambda_fnorm, ...
    dx_history, ...
    beta_history, ...
    ori_obj_part_list, ...
    eta_state_final, ...
    eta_update_history, ...
    eta_update_count, ...
    actual_iter, ...
    final_error, ...
    final_r, ...
    final_dxy ...
] = splitadmm20240119_mex( ...
    A, ...
    G, ...
    eta_state, ...
    beta0, ...
    c, ...
    outer_id, ...
    maxiter, ...
    X, ...
    Y, ...
    epsi, ...
    use_adaptive_beta, ...
    opts)
%SPLITADMM20240119_MEX
%
% Thin MATLAB wrapper around matrix_admm_mex.
%
% This MEX implementation supports the production configuration:
%
%   matrix_clean = true
%   beta_mode    = "fixed"
%   fixed c
%   fixed beta
%
% The output signature intentionally matches splitadmm20240119.m exactly,
% so solve_matrix_batching.m can switch backend without changing the rest
% of the experiment pipeline.

%#ok<INUSD>
% outer_id and use_adaptive_beta are retained for interface compatibility.


%% ======================== Validate MEX availability =====================

    if exist('matrix_admm_mex','file') ~= 3

        error( ...
            ['matrix_admm_mex is not compiled or not on the MATLAB path.\n', ...
             'Run methods/matrix/mex/compile_matrix_mex.m first.']);
    end


%% ======================== Validate supported mode =======================

    if ...
            ~isfield(opts,'matrix_clean') ...
            || ...
            ~logical(opts.matrix_clean)

        error( ...
            ['The current MEX implementation requires ', ...
             'opts.matrix_clean=true.']);
    end


    if ...
            ~isfield(opts,'beta_mode') ...
            || ...
            string(opts.beta_mode) ~= "fixed"

        error( ...
            ['The current MEX implementation supports only ', ...
             'opts.beta_mode="fixed".']);
    end


    if ...
            use_adaptive_beta ...
            || ...
            ( ...
                isfield(opts,'use_adaptive_beta') ...
                && ...
                logical(opts.use_adaptive_beta) ...
            )

        error( ...
            'MEX production path does not support adaptive beta.');
    end


%% ======================== Pass runtime parameters =======================

    mex_opts = ...
        opts;


% Ensure that the MEX receives the ACTUAL values passed into this solver,
% rather than depending on potentially stale fields in opts.

    mex_opts.c = ...
        c;

    mex_opts.beta0 = ...
        beta0;

    mex_opts.max_iter = ...
        maxiter;

    mex_opts.tol = ...
        epsi;


%% ======================== Run MEX =======================================

    [ ...
        X, ...
        Y, ...
        info ...
    ] = ...
        matrix_admm_mex( ...
            A, ...
            G, ...
            X, ...
            Y, ...
            eta_state, ...
            mex_opts);


%% ======================== Core scalar outputs ===========================

    flag = ...
        double(info.flag);


    eta_state_final = ...
        double(info.eta_state_final);


    eta_update_count = ...
        double(info.eta_update_count);


    actual_iter = ...
        double(info.iterations);


    final_error = ...
        double(info.final_error);


    final_r = ...
        double(info.final_r);


    final_dxy = ...
        double(info.final_dxy);


%% ======================== Clean-mode empty histories ====================

% Histories are intentionally not generated inside the C++ production
% kernel because they are not required by the algorithm and would increase
% both memory traffic and runtime.

    error_list = [];

    r_collect = [];
    dxy_collect = [];

    Lambda_history = ...
        cell(0,1);

    round_y_collect = [];
    y_non_ratio = [];

    lambda_fnorm = [];
    dx_history = [];

    beta_history = [];

    ori_obj_part_list = [];


% Keep exactly the same struct type used by the MATLAB solver.

    eta_update_history = struct( ...
        'outer_id',{}, ...
        'iteration',{}, ...
        'nnzY',{}, ...
        'dxy',{}, ...
        'eta_state_old',{}, ...
        'eta_state_new',{}, ...
        'eta_effective_old',{}, ...
        'eta_effective_new',{});

end