function [ ...
    X, ...
    Y, ...
    error_list, ...
    flag, ...
    Lambda_history, ...
    r_collect, ...
    dxy_collect, ...
    round_y_collect, ...
    y_non_ratio, ...
    lambda_fnorm, ...
    dx_history, ...
    beta_history, ...
    ori_obj_part_list, ...
    eta_state_final, ...
    eta_update_history, ...
    eta_update_count, ...
    actual_iter, ...
    final_error, ...
    final_r, ...
    final_dxy ...
] = splitadmm_vc( ...
    A, ...
    G, ...
    eta_state, ...
    beta0, ...
    c, ...
    outer_id, ...
    maxiter, ...
    X, ...
    Y, ...
    epsi, ...
    use_adaptive_beta, ...
    opts)
%SPLITADMM_VC
%
% Matrix-ADMM continuous solver used before Vc rounding.
%
% IMPORTANT DIFFERENCE FROM splitadmm20240119:
%
%   This solver does NOT wait for early_exist / near-binary Y.
%
%   It stops at the first scheduled iteration satisfying
%
%       eps_KKT =
%           max( ...
%               r, ...
%               ||X-Y||_F ...
%           )
%           <= opts.epsikkt.
%
% where
%
%   r =
%       || ...
%           0.5*(A*Y_new-A*Y_old) ...
%           + c*(Y_old-Y_new) ...
%       ||_F.
%
% After this function returns, solve_matrix_batching_vc constructs
%
%       S = Y*Y'
%
% and applies the SAME eADMM kequi_rounding Vc heuristic with 10 restarts.
%
% epsi is retained in the interface only for compatibility with the
% ordinary splitadmm20240119 signature. The VC branch uses opts.epsikkt
% as its stopping tolerance.


%% ======================== Defaults ======================================

    if ~isfield(opts,'matrix_clean')
        opts.matrix_clean = true;
    end

    if ~isfield(opts,'matrix_clean_fast')
        opts.matrix_clean_fast = true;
    end

    if ~isfield(opts,'matrix_detail')
        opts.matrix_detail = false;
    end

    if ~isfield(opts,'verbose')
        opts.verbose = false;
    end

    if ~isfield(opts,'print_every')
        opts.print_every = 100;
    end

    if ~isfield(opts,'stop_check_interval')
        opts.stop_check_interval = 10;
    end

    if ~isfield(opts,'epsikkt') || isempty(opts.epsikkt)

        error( ...
            ['splitadmm_vc requires opts.epsikkt. ', ...
             'Example: opts.epsikkt = 1e-3;']);
    end

    if ~isscalar(opts.epsikkt) || ...
            ~isfinite(opts.epsikkt) || ...
            opts.epsikkt <= 0

        error( ...
            'opts.epsikkt must be a positive finite scalar.');
    end

    if ~isfield(opts,'eta_adapt_enabled')
        opts.eta_adapt_enabled = false;
    end

    if ~isfield(opts,'eta')
        opts.eta = max(eta_state,0);
    end

    if ~isfield(opts,'eta_stage_initial')
        opts.eta_stage_initial = -1;
    end

    if ~isfield(opts,'eta_stagnation_iters')
        opts.eta_stagnation_iters = 100;
    end

    if ~isfield(opts,'eta_growth_factor')
        opts.eta_growth_factor = 1.1;
    end

    if ~isfield(opts,'eta_max')
        opts.eta_max = opts.eta;
    end

    if ~isfield(opts,'beta_mode')
        opts.beta_mode = "fixed";
    end

    if ~isfield(opts,'kabeta')
        opts.kabeta = 1;
    end

    if ~isfield(opts,'beta_switch_iter')
        opts.beta_switch_iter = 1000;
    end


%% ======================== Modes =========================================

    matrix_clean = ...
        logical(opts.matrix_clean);

    matrix_clean_fast = ...
        logical(opts.matrix_clean_fast);

    matrix_detail = ...
        logical(opts.matrix_detail);

    beta_mode = ...
        string(opts.beta_mode);

    epsikkt = ...
        double(opts.epsikkt);

    fprintf( ...
    ['[splitadmm_vc runtime] ', ...
     'matrix_clean=%d | ', ...
     'matrix_clean_fast=%d | ', ...
     'beta_mode=%s | ', ...
     'adaptive_beta=%d | ', ...
     'stop_interval=%d | ', ...
     'epsikkt=%.3e\n'], ...
    matrix_clean, ...
    matrix_clean_fast, ...
    char(beta_mode), ...
    logical(use_adaptive_beta), ...
    opts.stop_check_interval, ...
    epsikkt);
%% ======================== Dimensions ====================================

    [N,B] = size(G);

    if ~isequal(size(A),[N,N])

        error( ...
            'A must be N-by-N where G is N-by-B.');
    end

    if ~isequal(size(X),[N,B]) || ...
            ~isequal(size(Y),[N,B])

        error( ...
            'Initial X and Y must both be N-by-B.');
    end


%% ======================== Constants =====================================

    inv_c = 1/c;
    half_inv_c = 0.5/c;

    inv_N = 1/N;
    inv_B = 1/B;


%% ======================== Initial state =================================

    Lambda = ...
        zeros(N,B);

    AY = ...
        A*Y;

    beta = ...
        beta0;

    p0 = ...
        max(norm(X-Y,'fro'),eps);


%% ======================== Output histories ==============================

    error_list = [];

    r_collect = [];
    dxy_collect = [];

    round_y_collect = [];
    y_non_ratio = [];

    Lambda_history = cell(0,1);

    lambda_fnorm = [];
    dx_history = [];

    beta_history = [];

    ori_obj_part_list = [];


%% ======================== Scalar outputs ================================

    flag = 0;

    actual_iter = 0;

    final_error = NaN;
    final_r = NaN;
    final_dxy = NaN;


%% ======================== eta continuation ==============================

    eta_update_history = struct( ...
        'outer_id',{}, ...
        'iteration',{}, ...
        'nnzY',{}, ...
        'dxy',{}, ...
        'eta_state_old',{}, ...
        'eta_state_new',{}, ...
        'eta_effective_old',{}, ...
        'eta_effective_new',{});

    eta_update_count = 0;


    current_nnz = ...
        nnz(Y);

    eta_monitoring = ...
        opts.eta_adapt_enabled ...
        && ...
        eta_state < opts.eta_max ...
        && ...
        current_nnz > N;

    eta_best_nnz = ...
        current_nnz;

    eta_no_improvement = ...
        0;


%% ======================== Fast prox cache ===============================

    [ ...
        eta_effective, ...
        prox_threshold, ...
        prox_acos_coeff ...
    ] = ...
        make_eta_cache_vc( ...
            eta_state, ...
            c);


%% ======================== Optional header ===============================

    if opts.verbose

        fprintf('\n');
        fprintf('============================================================\n');
        fprintf('[Matrix-VC continuous stage]\n');
        fprintf('epsikkt = %.6e\n',epsikkt);
        fprintf('stop_check_interval = %d\n',opts.stop_check_interval);
        fprintf('early_exist is NOT used in splitadmm_vc.\n');
        fprintf('============================================================\n');
    end


%% ======================== Main loop =====================================

    for iter = 1:maxiter

        actual_iter = iter;


        %% ---------------------------------------------------------------
        % beta
        % ---------------------------------------------------------------

        if ...
                ~use_adaptive_beta ...
                || ...
                beta_mode=="fixed"

            beta = ...
                beta0;

        else

            pk = ...
                max(norm(X-Y,'fro'),eps);

            beta = ...
                choose_beta_vc( ...
                    beta_mode, ...
                    beta0, ...
                    opts.kabeta, ...
                    p0, ...
                    pk, ...
                    iter, ...
                    opts.beta_switch_iter, ...
                    Y, ...
                    N);
        end


        %% ---------------------------------------------------------------
        % X update
        % ---------------------------------------------------------------

        X = ...
            Y ...
            - ...
            inv_c*Lambda ...
            - ...
            half_inv_c*AY ...
            - ...
            inv_c*G;


        % Balanced-assignment affine projection.

        eX = ...
            sum(X,1);

        row_correction = ...
            ( ...
                1 ...
                + ...
                sum(eX)*inv_N ...
                - ...
                sum(X,2) ...
            ) ...
            * ...
            inv_B;

        X = ...
            X ...
            - ...
            eX*inv_N ...
            + ...
            row_correction;


        %% ---------------------------------------------------------------
        % Y update
        % ---------------------------------------------------------------

        Y_old = ...
            Y;

        AX = ...
            A*X;

        Y_bar = ...
            X ...
            + ...
            inv_c*Lambda ...
            - ...
            half_inv_c*AX;


        if eta_effective == 0

            % eta=0 warm stage.

            Y = ...
                min( ...
                    max(Y_bar,0), ...
                    1);

        else

            lambda_half = ...
                2*eta_effective/c;


            if matrix_clean_fast

                % --------------------------------------------------------
                % Fast but algebraically equivalent global threshold.
                % --------------------------------------------------------

                Y = ...
                    zeros(N,B);

                active = ...
                    Y_bar >= prox_threshold;


                if any(active(:))

                    v = ...
                        Y_bar(active);

                    arg = ...
                        prox_acos_coeff ...
                        ./ ...
                        (v.*sqrt(v));

                    arg = ...
                        min( ...
                            max(arg,-1), ...
                            1);

                    y = ...
                        (2/3) ...
                        .* ...
                        v ...
                        .* ...
                        ( ...
                            1 ...
                            + ...
                            cos( ...
                                2*pi/3 ...
                                - ...
                                (2/3)*acos(arg) ...
                            ) ...
                        );

                    y = ...
                        min(y,1);

                    Y(active) = ...
                        y;
                end


            else

                % --------------------------------------------------------
                % Reference L1/2 prox.
                % --------------------------------------------------------

                Y = ...
                    zeros(N,B);

                candidate_threshold = ...
                    (3/4) ...
                    * ...
                    lambda_half^(2/3);

                active = ...
                    Y_bar > candidate_threshold;


                if any(active(:))

                    v = ...
                        Y_bar(active);

                    arg = ...
                        (lambda_half/8) ...
                        .* ...
                        (v/3).^(-1.5);

                    arg = ...
                        min( ...
                            max(arg,-1), ...
                            1);

                    y = ...
                        (2/3) ...
                        .* ...
                        v ...
                        .* ...
                        ( ...
                            1 ...
                            + ...
                            cos( ...
                                2*pi/3 ...
                                - ...
                                (2/3)*acos(arg) ...
                            ) ...
                        );


                    lose_to_zero = ...
                        (y-v).^2 ...
                        + ...
                        lambda_half*sqrt(max(y,0)) ...
                        - ...
                        v.^2 ...
                        > ...
                        0;

                    y(lose_to_zero) = ...
                        0;

                    y = ...
                        min(y,1);

                    Y(active) = ...
                        y;
                end
            end
        end


        current_nnz = ...
            nnz(Y);


        %% ---------------------------------------------------------------
        % A*Y and Lambda
        % ---------------------------------------------------------------

        AY_new = ...
            A*Y;


        Lambda = ...
            Lambda ...
            + ...
            beta*(X-Y);


        %% ---------------------------------------------------------------
        % KKT stopping check
        %
        % This is the ONLY normal stopping rule for Matrix-VC.
        % ---------------------------------------------------------------

        stop_due = ...
            mod(iter,opts.stop_check_interval)==0 ...
            || ...
            iter==maxiter;


        if stop_due

            dxy = ...
                norm(X-Y,'fro');


            residual_matrix = ...
                0.5*(AY_new-AY) ...
                + ...
                c*(Y_old-Y);


            r = ...
                norm( ...
                    residual_matrix, ...
                    'fro');


            kkt_error = ...
                max(r,dxy);


            final_error = ...
                kkt_error;

            final_r = ...
                r;

            final_dxy = ...
                dxy;


            if ~matrix_clean

                error_list(end+1,1) = ...
                    kkt_error; %#ok<AGROW>

                r_collect(end+1,1) = ...
                    r; %#ok<AGROW>

                dxy_collect(end+1,1) = ...
                    dxy; %#ok<AGROW>
            end


            if ...
                    opts.verbose ...
                    && ...
                    mod(iter,opts.print_every)==0

                fprintf( ...
                    ['Matrix-VC iter=%d | eta_state=%.6g | ', ...
                     'eta_eff=%.6g | nnzY=%d | ', ...
                     'r=%.3e | dxy=%.3e | KKT=%.3e\n'], ...
                    iter, ...
                    eta_state, ...
                    eta_effective, ...
                    current_nnz, ...
                    r, ...
                    dxy, ...
                    kkt_error);
            end


            % ============================================================
            % KKT STOP
            % ============================================================

            if kkt_error <= epsikkt

                flag = 3;

                AY = ...
                    AY_new;

                break;
            end
        end


        %% ---------------------------------------------------------------
        % Optional histories
        % ---------------------------------------------------------------

        if ~matrix_clean

            beta_history(end+1,1) = ...
                beta; %#ok<AGROW>

            lambda_fnorm(end+1,1) = ...
                norm(Lambda,'fro'); %#ok<AGROW>

            dx_history(end+1,1) = ...
                norm(Y-Y_old,'fro'); %#ok<AGROW>


            if matrix_detail

                round_y_collect(end+1,1) = ...
                    max( ...
                        abs( ...
                            Y(:) ...
                            - ...
                            round(Y(:)))); %#ok<AGROW>


                y_non_ratio(end+1,1) = ...
                    mean( ...
                        Y(:)>1e-8 ...
                        & ...
                        Y(:)<1-1e-8); %#ok<AGROW>


                Lambda_history{end+1,1} = ...
                    Lambda; %#ok<AGROW>


                linear_part = ...
                    0.5*sum(sum(X.*AY_new)) ...
                    + ...
                    sum(sum(G.*X));

                lhalf_part = ...
                    eta_effective ...
                    * ...
                    sum( ...
                        sqrt( ...
                            max(Y(:),0)));

                ori_obj_part_list(end+1,1) = ...
                    linear_part ...
                    + ...
                    lhalf_part; %#ok<AGROW>
            end
        end


        %% ---------------------------------------------------------------
        % eta continuation
        % ---------------------------------------------------------------

        if ...
                opts.eta_adapt_enabled ...
                && ...
                eta_state < opts.eta_max


            if current_nnz <= N

                eta_monitoring = ...
                    false;

                eta_best_nnz = ...
                    current_nnz;

                eta_no_improvement = ...
                    0;


            elseif ~eta_monitoring

                eta_monitoring = ...
                    true;

                eta_best_nnz = ...
                    current_nnz;

                eta_no_improvement = ...
                    0;


            elseif current_nnz < eta_best_nnz

                eta_best_nnz = ...
                    current_nnz;

                eta_no_improvement = ...
                    0;


            else

                eta_no_improvement = ...
                    eta_no_improvement + 1;
            end


            if ...
                    eta_monitoring ...
                    && ...
                    eta_no_improvement ...
                    >= ...
                    opts.eta_stagnation_iters


                eta_old = ...
                    eta_state;


                eta_state = ...
                    next_eta_state_vc( ...
                        eta_state, ...
                        opts.eta_stage_initial, ...
                        opts.eta, ...
                        opts.eta_growth_factor, ...
                        opts.eta_max);


                eta_update_count = ...
                    eta_update_count + 1;


                if ~matrix_clean

                    eta_update_history(end+1) = struct( ... %#ok<AGROW>
                        'outer_id',outer_id, ...
                        'iteration',iter, ...
                        'nnzY',current_nnz, ...
                        'dxy',norm(X-Y,'fro'), ...
                        'eta_state_old',eta_old, ...
                        'eta_state_new',eta_state, ...
                        'eta_effective_old',max(eta_old,0), ...
                        'eta_effective_new',max(eta_state,0));
                end


                eta_best_nnz = ...
                    current_nnz;

                eta_no_improvement = ...
                    0;


                [ ...
                    eta_effective, ...
                    prox_threshold, ...
                    prox_acos_coeff ...
                ] = ...
                    make_eta_cache_vc( ...
                        eta_state, ...
                        c);
            end
        end


        %% ---------------------------------------------------------------
        % Advance
        % ---------------------------------------------------------------

        AY = ...
            AY_new;
    end


%% ======================== Max-iteration fallback ========================

    if flag ~= 3

        if ~isfinite(final_dxy)

            final_dxy = ...
                norm(X-Y,'fro');
        end

        if ~isfinite(final_r)

            AY_new = ...
                A*Y;

            residual_matrix = ...
                0.5*(AY_new-AY) ...
                + ...
                c*(Y_old-Y);

            final_r = ...
                norm( ...
                    residual_matrix, ...
                    'fro');
        end

        final_error = ...
            max( ...
                final_r, ...
                final_dxy);
    end


%% ======================== Final eta =====================================

    eta_state_final = ...
        eta_state;

end


% =========================================================================
% eta continuation helper
% =========================================================================

function eta_new = next_eta_state_vc( ...
    eta_old, ...
    eta_stage_initial, ...
    eta_positive_start, ...
    eta_growth, ...
    eta_max)

    if eta_old < 0

        if eta_old <= eta_stage_initial

            eta_new = ...
                0.5*eta_old;

        else

            eta_new = ...
                0;
        end

    elseif eta_old == 0

        eta_new = ...
            eta_positive_start;

    else

        eta_new = ...
            min( ...
                eta_growth*eta_old, ...
                eta_max);
    end
end


% =========================================================================
% fast prox cache
% =========================================================================

function [ ...
    eta_effective, ...
    threshold, ...
    acos_coeff ...
] = make_eta_cache_vc( ...
    eta_state, ...
    c)

    eta_effective = ...
        max(eta_state,0);


    if eta_effective == 0

        threshold = NaN;
        acos_coeff = NaN;

        return;
    end


    lambda_half = ...
        2*eta_effective/c;


    threshold = ...
        (3/2^(5/3)) ...
        * ...
        lambda_half^(2/3);


    acos_coeff = ...
        3*sqrt(3) ...
        * ...
        lambda_half ...
        / ...
        8;

end


% =========================================================================
% adaptive beta helper
% =========================================================================

function beta = choose_beta_vc( ...
    beta_mode, ...
    beta0, ...
    kabeta, ...
    p0, ...
    pk, ...
    iter, ...
    beta_switch_iter, ...
    Y, ...
    N)

    adaptive_beta = ...
        beta0 ...
        * ...
        min( ...
            1, ...
            kabeta*p0 ...
            / ...
            ( ...
                max(iter,1) ...
                * ...
                log(iter+1)^2 ...
                * ...
                max(pk,eps) ...
            ));


    switch beta_mode

        case "adaptive"

            beta = ...
                adaptive_beta;


        case "fix_then_adaptive"

            if iter <= beta_switch_iter

                beta = beta0;

            else

                beta = adaptive_beta;
            end


        case "adaptive_then_fix"

            if iter <= beta_switch_iter

                beta = adaptive_beta;

            else

                beta = beta0;
            end


        case "adaptive_until_binary"

            if nnz(Y) <= N

                beta = beta0;

            else

                beta = adaptive_beta;
            end


        otherwise

            error( ...
                'Unknown Matrix beta_mode: %s', ...
                char(beta_mode));
    end
end